kind: pipeline
name: k3d

steps:
- name: k3d-kubectl-get-nodes
  image: ghcr.io/oxr463/drone-plugin-k3d
  settings:
    command: kubectl get nodes
  volumes:
  - name: docker
    path: /var/run

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: docker
    path: /var/run

volumes:
- name: docker
  temp: {}
